version: '3.4'

networks:
  network-dev:
    driver: bridge 

services:
  # privatlyapi:
  #   image: privatlyapi:latest
  #   depends_on:
  #     - "postgres_image"
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - "80:80"
  #   environment:
  #     DB_CONNECTION_STRING: "host=postgres_image;port=5432;database=privatlyapi;username=admin;password=password"
  #   networks:
  #     - network-dev  
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
        - network-dev
  postgres_image:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - db_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "privatlyapi"
    networks:
      - network-dev
volumes:
  db_volume: